apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-hn
  namespace: default
  labels:
    app: client-hn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-hn
  template:
    metadata:
      labels:
        app: client-hn
    spec:
      hostNetwork: true
      securityContext:
        privileged: true
      containers:
        - name: client-hn
          image: quay.io/smalleni/netperf:latest
          command: ["sleep", "inf"]
          env:
            - name: nthr
              value: "1"
            - name: size
              value: "64K"
            - name: uperf_service_host
              value: "$(SERVER_SERVICE_HOST)"
            - name: uperf_service_port_uperf_data
              value: "$(SERVER_SERVICE_PORT_PORT30000)"
          volumeMounts:
            - name: throughput-volume
              mountPath: /tmp/throughput
            - name: rr-volume
              mountPath: /tmp/rr
      volumes:
        - name: throughput-volume
          configMap:
            name: throughput-config
            items:
              - key: throughput.xml
                path: throughput.xml
        - name: rr-volume
          configMap:
            name: rr-config
            items:
              - key: rr.xml
                path: rr.xml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 0
