apiVersion: v1
kind: Service
metadata:
  labels:
    app: netperf-server
  name: netperf-server
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 12865-12865
    port: 12865
    protocol: TCP
    targetPort: 12865
  - name: data
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: data1
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: data2
    port: 10002
    protocol: TCP
    targetPort: 10002
  - name: data3
    port: 10003
    protocol: TCP
    targetPort: 10003
  selector:
    app: netperf-server
  sessionAffinity: None
  type: ClusterIP
