apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netperf-server-hn
  name: netperf-server-hn
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: netperf-server-hn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cpu-quota.crio.io: disable
        irq-load-balancing.crio.io: disable
      labels:
        app: netperf-server-hn
    spec:
      containers:
      - command:
        - netserver
        - -D
        image: quay.io/cloud-bulldozer/k8s-netperf
        imagePullPolicy: Always
        name: k8s-netperf
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      runtimeClassName: performance-perf-profile
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
