apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      hostNetwork: true
      securityContext:
        privileged: true
      containers:
      - name: server
        image: quay.io/smalleni/netperf:latest
        command: ["/bin/sh", "-c"]
        args: ["/usr/sbin/nginx; iperf3 -s -D && uperf -s"]
        ports:
        - containerPort: 5201
          name: iperf3
        - containerPort: 20000
          name: uperf-control
        - containerPort: 40000
          name: uperf-data
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: http2
      terminationGracePeriodSeconds: 0
