apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-hn-pp
  namespace: default
  labels:
    app: server-hn-pp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-hn-pp
  template:
    metadata:
      annotations:
        # Disable CPU balance with CRIO
        irq-load-balancing.crio.io: "disable"
        cpu-load-balancing.crio.io: "disable"
        cpu-quota.crio.io: "disable"
      labels:
        app: server-hn-pp
    spec:
      runtimeClassName: performance-perf-profile
      hostNetwork: true
      securityContext:
        privileged: true
      containers:
        - name: server-hn-pp
          image: quay.io/smalleni/netperf:latest
          command: ["/bin/sh", "-c"]
          args: ["/usr/sbin/nginx; iperf3 -s -D && uperf -s"]
          ports:
            - containerPort: 5201
              name: iperf3
            - containerPort: 20000
              name: uperf-control
            - containerPort: 30000
              name: uperf-data
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: http2
          resources:
            requests:
              cpu: "4"
              memory: 1024M
            limits:
              cpu: "4"
              memory: 1024M
      terminationGracePeriodSeconds: 0
