apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-hn
  namespace: default
  labels:
    app: server-hn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-hn
  template:
    metadata:
      labels:
        app: server-hn
    spec:
      hostNetwork: true
      securityContext:
        privileged: true
      containers:
        - name: server-hn
          image: quay.io/smalleni/netperf:latest
          command: ["/bin/sh", "-c"]
          args: ["/usr/sbin/nginx; iperf3 -s -D && uperf -s"]
          ports:
            - containerPort: 5201
              name: iperf3
            - containerPort: 20000
              name: uperf-control
            - containerPort: 40000
              name: uperf-data
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: http2
      terminationGracePeriodSeconds: 0
