apiVersion: v1
kind: Service
metadata:
  name: server-pp
  namespace: istio-perf
spec:
  ports:
    - name: iperf3
      port: 5201
      protocol: TCP
      targetport: 5201
    - name: uperf-control
      port: 20000
      protocol: TCP
      targetport: 20000
      appProtocol: tls # Required for uperf. https://istio.io/latest/docs/ops/deployment/application-requirements/#server-first-protocols
    - name: uperf-data
      port: 30000
      protocol: TCP
      targetport: 30000
      appProtocol: tls # Required for uperf. https://istio.io/latest/docs/ops/deployment/application-requirements/#server-first-protocols
    - name: http
      port: 8080
      protocol: TCP
      targetport: 8080
    - name: http2
      port: 8443
      protocol: TCP
      targetport: 8443
  selector:
    app: server-pp
